apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeCluster
metadata:
  name: a-team-ck
spec:
  id: a-team-ck
  compositionRef:
    name: cluster-civo
  parameters:
    nodeSize: medium
    minNodeCount: 1
