apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-postgresql-official
  labels:
    provider: azure-official
    db: postgresql
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQL
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: resourcegroup
    base:
      apiVersion: azure.upbound.io/v1beta1
      kind: ResourceGroup
      spec:
        forProvider:
          location: eastus
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.name
  - name: server
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: Server
      spec:
        forProvider:
          location: eastus
          resourceGroupNameSelector:
            matchControllerRef: true
          storageMb: 5120
          autoGrowEnabled: true
          skuName: B_Gen5_2
          sslEnforcementEnabled: false
          sslMinimalTlsVersionEnforced: TLSEnforcementDisabled
          administratorLogin: postgres
          administratorLoginPasswordSecretRef:
            key: password
          publicNetworkAccessEnabled: true
        writeConnectionSecretToRef:
          namespace: crossplane-system
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.id
      toFieldPath: spec.writeConnectionSecretToRef.name
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace
    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.forProvider.version
    - fromFieldPath: spec.parameters.size
      toFieldPath: spec.forProvider.skuName
      transforms:
      - type: map
        map:
          small: B_Gen5_2
          medium: B_Gen5_4
          large: B_Gen5_8
    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.forProvider.engineVersion
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-password"
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.namespace
    connectionDetails:
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
    - fromConnectionSecretKey: endpoint
    - fromConnectionSecretKey: port
  - name: firewall-rule
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: FirewallRule
      spec:
        forProvider:
          startIpAddress: 0.0.0.0
          endIpAddress: 255.255.255.255
          resourceGroupNameSelector:
            matchControllerRef: true
          serverNameSelector:
            matchControllerRef: true
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
  - name: sql-config
    base:
      apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: ProviderConfig
      metadata:
        name: default
      spec:
        credentials:
          source: PostgreSQLConnectionSecret
          connectionSecretRef:
            namespace: crossplane-system
        sslMode: require
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.id
      toFieldPath: spec.credentials.connectionSecretRef.name
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.credentials.connectionSecretRef.namespace
    readinessChecks:
      - type: None
  - name: sql-db
    base:
      apiVersion: postgresql.sql.crossplane.io/v1alpha1
      kind: Database
      spec:
        forProvider: {}
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
    readinessChecks:
      - type: None
