apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: a-team-mysql-01
spec:
  id: a-team-mysql-01
  compositionSelector:
    matchLabels:
      provider: google
      db: mysql
  parameters:
    version: "8_0"
    size: small
