{
 "title": "Crossplane",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Statuses",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (kube_customresource_status_condition{customresource_kind=\"DatabaseInstance\", condition=\"Ready\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Claims",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name, namespace) (kube_customresource_status_condition{customresource_kind=\"SQLClaim\", condition=\"Ready\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cluster Statuses",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (kube_customresource_status_condition{customresource_kind=\"Cluster\", condition=\"Ready\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Claims",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(name, namespace) (kube_customresource_status_condition{customresource_kind=\"ClusterClaim\", condition=\"Ready\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}